kind: wasmer.io/App.v0
name: gymsaas
owner: idkrealyyea
package: .
locality:
  regions:
  - fr-roub1
env:
  NODE_ENV: production
  TRUST_PROXY: '1'
capabilities:
  database:
    engine: postgres
annotations:
  anybuild.run/config:
    commands:
      build: npm run build
      start: node server.mjs
    edgejs_enable: true
    edgejs_precompile: true
    name: out
    node_install_inputs:
    - package.json
    node_package_manager: npm
    node_package_name: gymsaas
    node_remove_native_binaries: true
    node_server: node
    node_build_command: "npx -y next-bundle@1.0.0 --build-command 'npm run build'"
    node_framework: next
  anybuild.run/provider: node
  anybuild.run/version: 0.28.0
  wasmer.io/version: 7.3.0
enableDatabase: true
app_id: da_R8EIJtNU7BdZ
